# title: "Dad’s Name"
description: "A life worth sharing"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

minimal_mistakes_skin: default

author:
  name: "Bhai Inderjeet Singh Ji"
  avatar: "/assets/images/Dad_Pic.jpg"
  bio: "A Life of Kirtan, Seva, and Devotion"

defaults:
- scope:
    path: ""
  values:
    author_profile: true

search: true
